name: Unit Tests with codacy coverage

permissions:
  contents: read
  issues: read
  pull-requests: read

on:
  push:
    branches: [ "main" ]
  
  pull_request:
    branches: [ "main" ]


jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable


      - name: Cache cargo-tarpaulin
        id: cache
        uses: actions/cache@v6
        with:
          path: ~/.cargo/bin/cargo-tarpaulin
          key: cargo-tarpaulin-${{ runner.os }}

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Run unit tests and generate tarpaulin report
        run: cargo tarpaulin --verbose --lib --out Xml --output-dir ./coverage

    
      - name: Upload to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/cobertura.xml


