name: Unit Tests


on:
  push:
    branches: [ "main" ]
  
  pull_request:
    branches: [ "main" ]


jobs:
  unit_tests:
    runs-on: latest-ubuntu

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run unit tests
        run: cargo test --all --verbose



